#Data added globally
metadata :
  author : 'Mike McFarland'
  github : 'http://github.com/mikedmcfarland'
prompts :
  - 'name'
  - key : 'license'
    default : 'ISC'
  - 'description'
cmds :
  - 'git init'
  - 'git remote add origin {{github}}/{{name}}.git'
  - 'git add -A'
  - 'npm install --save-dev gulp'
  - 'npm install'
